#!/usr/bin/env python3
"""Write, read, and remove a few landing_test records from production landing.

This is a narrowly scoped smoke test for a newly rebuilt production
``wind_tunnel_landing`` table.  It refuses to run unless production is empty,
copies a small number of valid records from ``landing_test`` with fresh IDs,
reads every copied record through ``WTGatewayClient``, then deletes only those
fresh IDs.

Usage:
    AWS_EC2_METADATA_DISABLED=true python scripts/migrations/production_landing_2026_07/smoke_test_production_landing.py
"""

import argparse
import sys
import uuid
from collections import defaultdict
from typing import Dict, List

from wt_sdk import WTGatewayClient
from wt_sdk.config import GatewayConfig, TableConfig
from wt_sdk.models import LandingRecord


SOURCE_TABLE = "landing_test"
TARGET_TABLE = "wind_tunnel_landing"


def _sql_string(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def _source_config() -> GatewayConfig:
    return GatewayConfig(tables=TableConfig(landing_table=SOURCE_TABLE))


def _target_config() -> GatewayConfig:
    return GatewayConfig(tables=TableConfig(landing_table=TARGET_TABLE))


def _cleanup_created_records(client: WTGatewayClient, records: List[LandingRecord]) -> int:
    """Delete only the IDs generated by this smoke test, using HASH pruning."""
    ids_by_job: Dict[str, List[str]] = defaultdict(list)
    for record in records:
        if record.job_id:
            ids_by_job[record.job_id].append(record.id)

    deleted = 0
    for job_id, record_ids in ids_by_job.items():
        id_list = ", ".join(_sql_string(record_id) for record_id in record_ids)
        deleted += client.delete_landing(
            f"job_id = {_sql_string(job_id)} AND id IN ({id_list})"
        )
    return deleted


def _load_source_records(
    client: WTGatewayClient,
    sample_size: int,
    source_bucket: int | None,
) -> List[LandingRecord]:
    """Find source rows through one HASH bucket at a time, avoiding a global scan."""
    buckets = [source_bucket] if source_bucket is not None else client._list_existing_partitions_for_table(SOURCE_TABLE)
    for bucket in buckets:
        rows = client.query_data(
            filter_query="job_id IS NOT NULL",
            partition=bucket,
            limit=sample_size,
            checkout_latest=True,
            exclude_none=False,
        )
        records = [LandingRecord.model_validate(row) for row in rows]
        usable_records = [record for record in records if record.job_id]
        if len(usable_records) >= sample_size:
            return usable_records[:sample_size]
    raise RuntimeError(
        f"Could not find {sample_size} landing_test rows with a non-null job_id in any existing HASH bucket"
    )


def run_smoke_test(sample_size: int, source_bucket: int | None) -> None:
    source_client = WTGatewayClient(config=_source_config())
    target_client = WTGatewayClient(config=_target_config())
    created_records: List[LandingRecord] = []
    try:
        existing_count = target_client.count_landing()
        if existing_count != 0:
            raise RuntimeError(
                f"Refusing smoke test: {TARGET_TABLE} contains {existing_count} existing rows"
            )

        source_records = _load_source_records(source_client, sample_size, source_bucket)

        test_prefix = f"production_smoke_{uuid.uuid4().hex}"
        created_records = [
            record.model_copy(update={"id": f"{test_prefix}_{index:03d}"}, deep=True)
            for index, record in enumerate(source_records)
        ]

        target_client.ingest_landing_batch(created_records)
        print(f"Wrote {len(created_records)} records to {TARGET_TABLE}.")

        for record in created_records:
            rows = target_client.query_data(
                filter_query=(
                    f"job_id = {_sql_string(record.job_id)} "
                    f"AND id = {_sql_string(record.id)}"
                ),
                limit=1,
                checkout_latest=True,
            )
            if len(rows) != 1 or rows[0]["id"] != record.id:
                raise RuntimeError(
                    f"Readback verification failed for test record {record.id}"
                )
        print("Client readback verified for every test record.")
    finally:
        try:
            if created_records:
                deleted = _cleanup_created_records(target_client, created_records)
                print(f"Removed {deleted} smoke-test records from {TARGET_TABLE}.")

            remaining_count = target_client.count_landing()
            if remaining_count != 0:
                raise RuntimeError(
                    f"Production landing cleanup check failed: {remaining_count} rows remain"
                )
            print(f"Cleanup verified: {TARGET_TABLE} contains 0 rows.")
        finally:
            source_client.close()
            target_client.close()


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Copy a few landing_test rows into empty production landing, read them back, then clean up."
    )
    parser.add_argument("--sample-size", type=int, default=3)
    parser.add_argument(
        "--source-bucket",
        type=int,
        default=None,
        help="Read samples from one known non-empty landing_test HASH bucket instead of scanning all buckets.",
    )
    args = parser.parse_args()
    if args.sample_size <= 0:
        parser.error("--sample-size must be greater than zero")

    try:
        run_smoke_test(args.sample_size, args.source_bucket)
    except Exception as exc:
        print(f"Production landing smoke test failed: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
